### ISSUE TITLE
multiplyPrice() vs. increasePrice ()

### ISSUE THREAD

**Issue by cantcool** [FrontenderMagazine/programmirovanie-klassami-v-veb-prilozheniyakh#2]
![Image](http://i.imgur.com/a0v2WOr.png)
multiplyPrice() vs. increasePrice ()

**Comment by iamstarkov** [comment]
простите, я не понял

**Comment by cantcool** [comment]
Видимо, забыли в одном месте переименовать метод: объявляется multiplyPrice(), а вызывается increasePrice()

**Comment by iamstarkov** [comment]
@vyushin поможешь?

**Comment by vyushin** [comment]
@iamstarkov, да, конечно. :)
@cantcool, тут явная опечатка, вы правы. :)

Должно быть `product.multiplyPrice(0.10);`

**Comment by cantcool** [comment]
@vyushin, но в остальных комментах и по тексту `increasePrice()` :)

**Comment by vyushin** [comment]
@cantcool, ахах. :+1:  Цепная реакция. ))
Исправил на increasePrice() чтобы править меньше
