### ISSUE TITLE
Мы только что создали новый класс Product

### ISSUE THREAD

**Issue by KarelWintersky** [FrontenderMagazine/programmirovanie-klassami-v-veb-prilozheniyakh#3]
`и все они будут содержать методы getDiscountedPrice и writeDiscountedPriceTo`

Тем не менее метод `writeDiscountedPriceTo` в классе не описан... нету у нас в примере `this.writeDiscountedPriceTo`. Как так?

---

Далее, "решение задачи по seniou'у" конечно отличное, но что с потреблением памяти? 10000 товаров - 10000 вызовов new Product({}) ? 

Ах, я вижу дальше модель с темплейтами и реплейсами для подстановки  значений. Так держать! Ну а чо, пускай браузер пашет, а если памяти не хватает - пускай еще купят.

**Comment by vyushin** [comment]
@KarelWintersky, я ответил вам в комментариях к статье. Дублирую тут:

> Хороший вопрос и правильный. Выше в комментах я говорил о методе addProducts для добавления товаров одним массивом. Это хардкодный вариант просто для наглядности. В реальности лучше подгружать этот массив аяксом с сервера в json или XML формате.
> В случае, когда у нас много товаров мы можем сделать пагинацию, аякс скроллинг и т. п., подгружая данные динамически.

**Comment by iamstarkov** [comment]
👍

**Comment by KarelWintersky** [comment]
Да, в комментариях удобнее :)

@iamstarkov квадратик с буквами 0IF44D - чтобы это значило? ;) знак фейспалма? :)

я думаю, иссью можно спокойно закрыть.

**Comment by iamstarkov** [comment]
квадратик значит эмодзи и он почему-то у тебя не поддерживается. вот так лучше :+1: ?

PS. линукс или виндоус XP?

**Comment by KarelWintersky** [comment]
win7
:+1:  поддерживается ;)
